#!/usr/bin/env sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SCENARIO_FILE="$ROOT/validation/pressure-scenarios.json"
REPORT_FILE="$ROOT/docs/pressure-simulation-report.md"

if [ ! -f "$SCENARIO_FILE" ]; then
  printf '%s\n' "Missing pressure scenario file: validation/pressure-scenarios.json" >&2
  exit 1
fi

mkdir -p "$ROOT/docs"

python_cmd=""
if command -v python3 >/dev/null 2>&1; then
  python_cmd="python3"
elif command -v python >/dev/null 2>&1; then
  python_cmd="python"
else
  printf '%s\n' "python3/python is required for pressure simulation" >&2
  exit 1
fi

"$python_cmd" - "$ROOT" "$SCENARIO_FILE" "$REPORT_FILE" <<'PY'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
scenario_file = pathlib.Path(sys.argv[2])
report_file = pathlib.Path(sys.argv[3])

data = json.loads(scenario_file.read_text(encoding="utf-8"))
errors = []
report = ["# Pressure Simulation Report", "", "Generated by `scripts/simulate-pressure.sh`.", ""]

for scenario in data["scenarios"]:
    passed = True
    report.append(f"## {scenario['id']}: {scenario['name']}")
    report.append("")
    report.append(f"User request: {scenario['user_request']}")
    report.append("")
    report.append("Expected path: " + " -> ".join(f"`{item}`" for item in scenario["expected_path"]))
    report.append("")
    report.append("Checks:")

    for check in scenario["required_evidence"]:
        skill_file = root / "skills" / check["skill"] / "SKILL.md"
        if not skill_file.exists():
            passed = False
            msg = f"Missing skill file for {check['skill']}"
            errors.append(f"{scenario['id']}: {msg}")
            report.append(f"- FAIL: {msg}")
            continue
        text = skill_file.read_text(encoding="utf-8")
        if check["contains"] in text:
            report.append(f"- PASS: `{check['skill']}` contains `{check['contains']}`")
        else:
            passed = False
            msg = f"`{check['skill']}` missing `{check['contains']}`"
            errors.append(f"{scenario['id']}: {msg}")
            report.append(f"- FAIL: {msg}")

    report.append("")
    report.append("Result: PASS" if passed else "Result: FAIL")
    report.append("")

failed = {err.split(":", 1)[0] for err in errors}
summary = f"Summary: {len(data['scenarios']) - len(failed)}/{len(data['scenarios'])} scenarios passed."
report.insert(2, summary)
report.insert(3, "")
report_file.write_text("\n".join(report) + "\n", encoding="utf-8")

if errors:
    for err in errors:
        print(f"- {err}", file=sys.stderr)
    sys.exit(1)

print(summary)
print("Report written to docs/pressure-simulation-report.md")
PY
