$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$scenarioPath = Join-Path $root "validation/pressure-scenarios.json"
$reportPath = Join-Path $root "docs/pressure-simulation-report.md"
$errors = New-Object System.Collections.Generic.List[string]

if (-not (Test-Path -LiteralPath $scenarioPath)) {
  Write-Error "Missing pressure scenario file: validation/pressure-scenarios.json"
  exit 1
}

$reportDir = Split-Path -Parent $reportPath
if (-not (Test-Path -LiteralPath $reportDir)) {
  New-Item -ItemType Directory -Path $reportDir | Out-Null
}

$scenarioData = Get-Content -Raw -LiteralPath $scenarioPath -Encoding UTF8 | ConvertFrom-Json
$report = New-Object System.Collections.Generic.List[string]
$report.Add("# Pressure Simulation Report") | Out-Null
$report.Add("") | Out-Null
$report.Add("Generated by `scripts/simulate-pressure.ps1`.") | Out-Null
$report.Add("") | Out-Null

foreach ($scenario in $scenarioData.scenarios) {
  $scenarioPass = $true
  $report.Add("## $($scenario.id): $($scenario.name)") | Out-Null
  $report.Add("") | Out-Null
  $report.Add("User request: $($scenario.user_request)") | Out-Null
  $report.Add("") | Out-Null
  $report.Add("Expected path: " + (($scenario.expected_path | ForEach-Object { [string]$_ }) -join " -> ")) | Out-Null
  $report.Add("") | Out-Null
  $report.Add("Checks:") | Out-Null

  foreach ($check in $scenario.required_evidence) {
    $skillFile = Join-Path $root ("skills/{0}/SKILL.md" -f $check.skill)
    if (-not (Test-Path -LiteralPath $skillFile)) {
      $scenarioPass = $false
      $message = "Missing skill file for $($check.skill)"
      $errors.Add("$($scenario.id): $message") | Out-Null
      $report.Add("- FAIL: $message") | Out-Null
      continue
    }

    $text = Get-Content -Raw -LiteralPath $skillFile -Encoding UTF8
    if ($text.Contains([string]$check.contains)) {
      $report.Add("- PASS: $($check.skill) contains $($check.contains)") | Out-Null
    } else {
      $scenarioPass = $false
      $message = "$($check.skill) missing $($check.contains)"
      $errors.Add("$($scenario.id): $message") | Out-Null
      $report.Add("- FAIL: $message") | Out-Null
    }
  }

  $report.Add("") | Out-Null
  if ($scenarioPass) {
    $report.Add("Result: PASS") | Out-Null
  } else {
    $report.Add("Result: FAIL") | Out-Null
  }
  $report.Add("") | Out-Null
}

$summary = "Summary: {0}/{1} scenarios passed." -f (($scenarioData.scenarios.Count - $errors.Count)), $scenarioData.scenarios.Count
if ($errors.Count -gt 0) {
  $failedScenarioIds = $errors | ForEach-Object { ($_ -split ":", 2)[0] } | Select-Object -Unique
  $summary = "Summary: {0}/{1} scenarios passed." -f ($scenarioData.scenarios.Count - $failedScenarioIds.Count), $scenarioData.scenarios.Count
}

$report.Insert(2, $summary)
$report.Insert(3, "")
$report | Set-Content -LiteralPath $reportPath -Encoding UTF8

if ($errors.Count -gt 0) {
  Write-Error (($errors | ForEach-Object { "- $_" }) -join [Environment]::NewLine)
  exit 1
}

Write-Output $summary
Write-Output "Report written to docs/pressure-simulation-report.md"
